# Creating a numpy array

In [2]:
import numpy as np

## One dimensional:

In [3]:
a = np.array([10, 20, 30])

In [4]:
a

array([10, 20, 30])

In [5]:
type(a)  # nd = n-dimensions

numpy.ndarray

## Getting array information: data type, dimensions, shape and size

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
a.size

3

In [9]:
a.nbytes

24

## Two dimensional:

In [10]:
a2 = np.array([[1,2,3], [4,5,6]])

In [11]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a2.dtype

dtype('int64')

In [13]:
a2.ndim

2

In [14]:
a2.shape

(2, 3)

In [15]:
a2.size

6

In [16]:
a2.nbytes

48

## Important: Arrays must have regular shapes!!!

In [3]:
np.array([[1,2,3], [4,5]])  # irregular shape: don't do this! 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

And also: array **size** usually does not change after creation.

# Specifying data types with `dtype` and `astype()`

In [18]:
np.array([10, 20, 30])

array([10, 20, 30])

In [19]:
np.array([10, 20, 30], dtype=float)

array([10., 20., 30.])

In [20]:
a.astype(float)

array([10., 20., 30.])

# More ways to create arrays

## `zeros()`, `ones()`, `empty()`

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((4, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.empty(10) # does not initalize memory

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##  `arange()`, `linspace()`

In [26]:
a3 = np.arange(20)  # creates actual array and not iteratable

In [27]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.arange(5.) # creates floats!

array([0., 1., 2., 3., 4.])

In [29]:
np.arange(10, 40, 5)

array([10, 15, 20, 25, 30, 35])

In [6]:
np.linspace(1, 10, 15)  # instead of calculating the size of each sterp, we define here the number of required elements and the step is calculated for us

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

## ...`eye()`, `diag()`

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.eye(8, k=2)

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.diag(np.arange(10))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

## `np.random.*`

In [34]:
np.random.random(10)

array([0.52297285, 0.79754644, 0.36816662, 0.46000435, 0.64712376,
       0.97199938, 0.65291903, 0.30065233, 0.10800028, 0.27023246])

In [35]:
np.random.random((3,5))

array([[0.59258109, 0.35775893, 0.21164484, 0.88275613, 0.89120151],
       [0.60319397, 0.08085025, 0.07080682, 0.45673067, 0.77097745],
       [0.72088694, 0.09743378, 0.83669466, 0.15414018, 0.92524497]])

In [36]:
np.random.randint(0, 10, (4, 6)) # creates ints from 0 to 9; excludes 10.

array([[3, 3, 9, 5, 8, 2],
       [9, 6, 1, 6, 4, 6],
       [8, 9, 3, 3, 3, 8],
       [8, 7, 4, 4, 0, 5]])

In [37]:
np.random.permutation(10) # random permutation of arange(10)

array([4, 0, 6, 2, 7, 8, 1, 9, 5, 3])