# Accessing Array Data: Indexing and Views

In [3]:
import numpy as np

In [4]:
a = np.linspace(10, 100, 10, dtype=int)

In [5]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Accessing array items (scalars)

In [6]:
a[0] # first item is #0

np.int64(10)

In [7]:
a[6]

np.int64(70)

In [8]:
a[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

### Reminder: negative indexing

In [9]:
a[-1]  # access the last element

np.int64(100)

In [10]:
type(a[0])

numpy.int64

## Creating slices

In [11]:
a_1 = a[2:4]

In [12]:
a_1

array([30, 40])

## A slice is a **view** of an array!!!

In [13]:
a_1[0] = 9999

In [14]:
a_1

array([9999,   40])

In [15]:
a  # regular slice creates a copy, slice of numpy array creates a view to the orignal array

array([  10,   20, 9999,   40,   50,   60,   70,   80,   90,  100])

In [16]:
a_1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [17]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

### We can always create a copy:

In [18]:
c = a[2:4].copy()

In [19]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

## Indexing in multi-dimensional arrays

In [20]:
b = np.arange(50).reshape(5, 10)

In [21]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
b[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b[3,5] = 999

In [24]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34, 999,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [25]:
b[:,0]

array([ 0, 10, 20, 30, 40])

In [26]:
col1 = b[:,0]

In [27]:
col1

array([ 0, 10, 20, 30, 40])

In [28]:
col1[3] = 1234

In [29]:
col1

array([   0,   10,   20, 1234,   40])

In [30]:
b

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1234,   31,   32,   33,   34,  999,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49]])

In [43]:
b[:,-1]  # get the last column

array([ 9, 19, 29, 39, 49])

In [32]:
b[-1]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [44]:
b[::-1,4:]

array([[ 44,  45,  46,  47,  48,  49],
       [ 34, 999,  36,  37,  38,  39],
       [ 24,  25,  26,  27,  28,  29],
       [ 14,  15,  16,  17,  18,  19],
       [  4,   5,   6,   7,   8,   9]])

**`[::-1]`**: This is slicing on the rows of the array. The `::` indicates slicing, and the `-1` indicates the step. The step `-1` means to reverse the order of the rows. So, `b[::-1]` reverses the rows of `b`

**`4:`**: This is slicing on the columns of the array. `4:` means "start from column index 4 and include all subsequent columns". So, `b[::-1, 4:]` will select columns from index 4 to the end, from the reversed rows array

### Accessing items in NumPy Array

In [40]:
b[2][3]  # This works, but not recommended - 2 actions - one for getting the row and second for the item

np.int64(23)

In [41]:
b[(2,3)]  # Better way - direct access to the item

np.int64(23)

In [42]:
b[2,3]  # The same as we can ommit () in tuples 

np.int64(23)

## 